# DataRoot University DS100 Test #2 Second Try
На проходження тесту виділяється 59 хвилин.

## Python

### 1.  Напишіть ф-цію - генератор паролів. Будьте креативними в тому, як ви створюєте паролі - сильні паролі містять малі та великі літери, цифри та символи. Паролі повинні бути випадковими. Ф-ція повинна створювати новий пароль кожного разу при її виклику. Ф-ція приймає параметр n (n > 6), який відповідає за довжину паролю.

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

### 2.  Реалізуйте ф-цію, яка перевіряє, чи є слово паліндромом:

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

In [21]:
def f(x):            
    for i in range(0, len(x)//2, 1):        
        if x[i] != x[-i-1]:
            return False
    return True
f('pallap')


True

### 3. Напишіть програму, яка приймає 2 невід'ємні цифри, X, Y як вхід і генерує 2-мірний масив. Значення елемента в i-му рядку і j-му стовпчику масиву має бути i * j, де i = 0, 1 .., X-1; j = 0, 1, .., Y-1.

Приклад:
Припустімо, що до програми наведені наступні входи:
3,5. 
Виходом програми має бути:
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

In [31]:
import numpy as np
X= 3
Y= 5
def f(X, Y):
    temp = np.ones((3,5))
    for i in range(0, X, 1):
        for j in range(0, Y, 1):
            temp[i,j] = i*j
    return temp
f(X,Y)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.]])

### 4. Реалізуйте клас Torus, який створюється за двома радіусами r, R, R > r. Містить два методи, які повертають відповідно: площу поверхні та об'єм.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 6хв
```

### 5.  Реалізуйте декоратор, який засікає час виконання ф-ції та логує його.

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 6хв
```

In [48]:
import time

def decorator(func):
    log ={}
    def helper(*args, **kw):               
        sttime = time.time()
        result = func(*args, **kw)
        endtime = time.time()
        log[str(func.__name__)] = int((endtime - sttime) * 1000)
        print(log)
    return helper

@decorator
def f(x):
    print(x)
    
f('hi')
f('die')

hi
{'f': 4}
die
{'f': 0}


## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Помножте масив розмірності (5, 5, 3), на масив розмірності (5,5).
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

In [56]:

X = np.ones((5,5,3))
Y = np.ones((5,5))
np.dot(X.T, Y)

array([[[ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.]],

       [[ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.]],

       [[ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.,  5.]]])

### 7. Поверніть з 2-вимірного масиву лінійно незалежні рядки.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 6хв
```

In [58]:
x = np.random.rand(3,4)
x

array([[ 0.18388303,  0.67977168,  0.2206586 ,  0.36051526],
       [ 0.84506626,  0.67783184,  0.38704641,  0.5485629 ],
       [ 0.0174291 ,  0.2341335 ,  0.44024787,  0.25039052]])

### 8. Створіть випадковий вектор розміру 20 і замініть мінімальне за модулем значення на 0
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

### Pandas

### 9. Скажімо, є DataFrame df зі стовпчиком "A" цілих чисел. Наприклад:


In [62]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

Відфільтруйте рядки, які містять таке ж число, як рядок, що безпосередньо вище.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

### 10. Скажімо, є DataFrame df з числовими значеннями:

In [11]:
df = pd.DataFrame(np.random.random(size=(5, 3)))

Відніміть середнє значення рядку від кожного елементу у відповідному рядку.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

### 11. Є DataFrame df зі стовпцями: групи - "grps" та значення - "vals":

In [13]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

Для кожної групи знайдіть суму трьох найбільших значень.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 3хв
```

## Scipy & Matplotlib

### 12. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами(завдання на повторення):

#### 12.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 12.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 12.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 12.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```